defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "journal"
      type: "posts"
    values:
      crumbtext: "Journal"
      crumblink: "/journal"
  -
    scope:
      path: "fiction"
      type: "posts"
    values:
      crumbtext: "Fiction"
      crumblink: "/fiction"
  -
    scope:
      path: "articles"
      type: "posts"
    values:
      crumbtext: "Articles"
      crumblink: "/articles"
  -
    scope:
      path: "guides"
      type: "posts"
    values:
      crumbtext: "Guides"
      crumblink: "/guides"
